'use strict'
/* eslint-disable no-unused-expressions */
/* global describe it */
// tests for queueMails
// Generated by serverless-mocha-plugin

const AWS = require('aws-sdk-mock')
const mochaPlugin = require('serverless-mocha-plugin')
const aws = require('aws-sdk')
AWS.setSDKInstance(aws)

const expect = mochaPlugin.chai.expect
const wrapped = mochaPlugin.getWrapper('sendEmail', '/src/delivery/mailgun/handler.js', 'sendEmail')

describe('Mailgun - Send Email', () => {
  it('Should exit the lambda if there are no records in the event', () => {
    return wrapped.run({}).catch((error) => {
      expect(error.message).to.be.eq('No record to process')
    })
  })

  it('Should return a successful response', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty
      expect(response).to.have.property('statusCode').to.equal(200)
    })
  })
})
